### ISSUE TITLE
unable to "run test" for this lab

### ISSUE THREAD

**Issue by trevored** [learn-co-curriculum/calculating-distance-lab#12]
I am unable to "run test" for this lab.

I'm not the only one who seems to be having this issue.

Can you please suggest a fix or perhaps update the platform so that tests can be run?

I'm on a Macbook, using Google Chrome.

**Comment by GenieMak** [comment]
I'm having the same issue. Also the interface is glitchy. I'll go to next Lesson but it's going to mark this one as incomplete.

**Comment by FilipPreo** [comment]
Yeah, I'm having the same issue.
