### ISSUE TITLE
Not understanding distance_between_neighbors_squared formula

### ISSUE THREAD

**Issue by DiffuseSingularity** [learn-co-curriculum/calculating-distance-lab#7]
The solution is as follows - 

def distance_between_neighbors_squared(first_neighbor, second_neighbor):
    return street_distance(first_neighbor, second_neighbor)**2 + avenue_distance(first_neighbor, second_neighbor)**2 

When, to me, A^2 + B^2 should be written as 
def distance_between_neighbors_squared(first_neighbor, second_neighbor):
    return street_distance(first_neighbor - second_neighbor)**2 + avenue_distance(first_neighbor - second_neighbor)**2

Why is it that A^2 for the problem is derived from (A1, A2)**2 rather than (A1 - A2)**2, and likewise (B1, B2)**2 rather than (B1 - B2)**2?

**Comment by mas16** [comment]
Hi DiffuseSingularity, thanks for your note! Take a look at how street_distance is defined in the solution.
